### ISSUE TITLE
In logs: "Cannot store the access token because dependencies are missing"

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-docker#33]
**Describe the bug**
Logs from `make subgraph`:

```
> circles-subgraph@1.0.0 deploy
> ./scripts/deploy.sh

graph deploy CirclesUBI/circles-subgraph --ipfs http://localhost:5001 --node http://localhost:8020 /.../circles-docker/.tmp/subgraph/.subgraph.tmp.yaml
Could not get access token from libsecret (usually gnome-keyring or ksecretservice): 

Cannot store the access token because dependencies are missing. If you
are on Linux, try installing 'libsecret-1-dev' (Debian, Ubuntu etc.) or
'libsecret-devel' (RedHat, Fedora etc.) and reinstalling Graph CLI
afterwards.

The original error was: Cannot find module 'keytar'
Require stack:
- /.../circles-docker/.tmp/subgraph/node_modules/@graphprotocol/graph-cli/src/command-helpers/auth.js
- /.../circles-docker/.tmp/subgraph/node_modules/@graphprotocol/graph-cli/src/commands/auth.js
- /.../circles-docker/.tmp/subgraph/node_modules/gluegun/build/loaders/module-loader.js
- /.../circles-docker/.tmp/subgraph/node_modules/gluegun/build/loaders/command-loader.js
- /.../circles-docker/.tmp/subgraph/node_modules/gluegun/build/runtime/runtime.js
- /.../circles-docker/.tmp/subgraph/node_modules/gluegun/build/domain/builder.js
- /.../circles-docker/.tmp/subgraph/node_modules/gluegun/build/index.js
- /.../circles-docker/.tmp/subgraph/node_modules/@graphprotocol/graph-cli/src/cli.js
- /.../circles-docker/.tmp/subgraph/node_modules/@graphprotocol/graph-cli/bin/graph
      
Continuing without an access token
```

**To Reproduce**
1. deploy docker containers:
    ```
    make down
    git pull
    make clean
    make up EXPOSE_PORTS=1
    make subgraph
    ```
2. See logs of the last command

**Expected behavior**
I expected no warnings.

**Desktop-Computer:**
 - OS: Debian 10

**Comment by llunaCreixent** [comment]
When I deploy the subgraph in local (without docker) the warnings don't appear and the `package-lock.json` file is automatically updated.

**Comment by llunaCreixent** [comment]
See: https://github.com/graphprotocol/graph-cli/issues/290

**Comment by llunaCreixent** [comment]
Do we have to install `libsecret`? 
See: https://github.com/graphprotocol/graph-cli/#on-linux

**Comment by adzialocha** [comment]
This script runs locally on your computer (so no docker involved). The graph client looks for the auth token and either you have it defined as an environment variable (see `.env.example`) or it will attempt looking into your keyring of your operating system (aka `gnome-keyring or ksecretservice` etc.). If you don't have any such application installed it will throw this warning.

So there is two ways to avoid this warning:

1. Set a (fake) auth token (could be done in your personal `.env` var or in the script if you want to override this behaviour for everyone else [think its ok for local development]: https://github.com/CirclesUBI/circles-docker/blob/main/scripts/deploy-subgraph.sh#L24)
2. Install a keyring manager on your computer :smile_cat:

**Comment by llunaCreixent** [comment]
Thank for the explanation :)
I did have `gnome-keyring` installed on my computer. The warning disappeared installing `libsecret-1-dev` in my Debian.
