### ISSUE TITLE
Integrate pathfinder2 services in docker setup 

### ISSUE THREAD

**Issue by JacqueGM** [CirclesUBI/circles-docker#65]
Create these services: blockchain-indexer, database, pathfinder-updater, pathfinder2 from  https://github.com/CirclesUBI/circles-platform/blob/main/ansible/roles/apps/templates/docker-compose.yaml.j2   in the docker setup.

**Comment by JacqueGM** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/circles-docker/65?planning-poker) with Zenhub @llunaCreixent

**Comment by louilinn** [comment]
Waiting for Jaensens implementation of updated schema

**Comment by almereyda** [comment]
We have found a race condition during initialisation of the indexer database.

- https://github.com/CirclesUBI/land-local/issues/2

A workaround is available.
