### ISSUE TITLE
Align pathfinder versions to what is production

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-docker#78]
For the new services that we integrated and are needed for the pathfinder service, we are using the `dev` version. We need to change it to reflect the specific versions that are used in prod.

Right now we use `dev` bc we assume this is what it's in prod. Ref: https://github.com/CirclesUBI/land-local/blob/main/modes/from-image/docker-compose.yml

But we'll use version ids when we integrate the services in our IAC.

**Comment by JacqueGM** [comment]
production version from GnoCi
